const authTypes = {
  AUTH_START: 'AUTH_START',
  AUTH_FAIL: 'AUTH_FAIL',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  VERIFY_ACCOUNT_START: 'VERIFY_ACCOUN_START',
  VERIFY_ACCOUNT_SUCCESS: 'VERIFY_ACCOUN_SUCCESS',
  VERIFY_ACCOUNT_FAIL: 'VERIFY_ACCOUN_FAIL',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_OUT_USER: 'SIGN_OUT_USER',
};

export default authTypes;
