const userTypes = {
  PROFILE_START: 'PROFILE_START',
  CREATE_PROFILE_SUCCESS: 'CREATE_PROFILE_SUCCESS',
  FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
  PROFILE_FAIL: 'PROFILE_FAIL',
};

export default userTypes;
